name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Java
      id: java
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA_RESULTS: "${{steps.java.outputs.result}}"
      with:
        runners: java
